include_module 'dotfile'

dotfile '.bash_aliases'
dotfile '.bash_profile'
dotfile '.bash_profile.d/000_locale.sh'
dotfile '.bash_profile.d/100_homebrew.sh'
dotfile '.bash_profile.d/101_cache.sh'
dotfile '.bash_profile.d/200_functions.sh'
dotfile '.bash_profile.d/500_rbenv.sh'
dotfile '.bash_profile.d/510_pyenv.sh'
dotfile '.bash_profile.d/900_home_bin.sh'
dotfile '.bash_profile.d/910_aliases.sh'

dotfile '.config/nvim/init.vim'

dotfile '.gemrc'
dotfile '.gitconfig'
dotfile '.tmux.conf'
dotfile '.dein.toml'
dotfile '.vimrc'

include_module 'homebrew'
include_module 'git'

execute 'brew update'

include_module 'mas'
include_module 'slack'
include_module 'tweetbot'
include_module 'evernote'
include_module 'quiver'
include_module 'todoist'
include_module 'lv'
include_module 'highway'
include_module 'xz'
include_module 'tmux'
include_module 'iterm2'
include_module 'peco'
include_module 'ghq'
include_module 'hub'
include_module 'postgresql'
include_module 'sdl2'
include_module 'envchain'
include_module 'amazon-ecs-cli'

include_module 'alfred'
include_module 'bartender'
include_module 'istat_menus'
include_module 'dropbox'
include_module '1password'
include_module 'papers'
include_module 'dash'
include_module 'google_chrome'
include_module 'skype'
include_module 'rescue_time'
include_module 'spark'
include_module 'docker'

include_module 'rbenv'
include_module 'ruby'
include_module 'gem-src'

execute 'rbenv global 2.4'

include_module 'pyenv'
include_module 'python'

include_module 'jupyter'
include_module 'iruby'

include_module 'julia'
include_module 'ijulia'

include_module 'r'
include_module 'irkernel'
include_module 'rstudio-desktop'

include_module 'neovim'
include_module 'wakatime'
include_module 'terraform'

include_module 'duet'
