include_module 'gdbm'
include_module 'gmp'
include_module 'libffi'
include_module 'libyaml'
include_module 'openssl'
include_module 'qdbm'
include_module 'readline'

include_recipe 'trunk'
include_recipe '2.4'
include_recipe '2.3'
include_recipe '2.2'
