include_module 'libtool'
include_module 'xz'

include_module 'libjpeg'
include_module 'libpng'
include_module 'libtiff'
include_module 'freetype'
include_module 'fontconfig'
include_module 'little-cms'
include_module 'little-cms2'
include_module 'libwmf'
include_module 'librsvg'
include_module 'liblqr'
include_module 'openexr'
include_module 'ghostscript'
include_module 'libwebp'
include_module 'openjpeg'
include_module 'fftw'
include_module 'pango'

package 'imagemagick'
