# Homebrew

PATH=/opt/brew/bin${PATH+:$PATH}
LD_LIBRARY_PATH=/opt/brew/lib${LD_LIBRARY_PATH+:$LD_LIBRARY_PATH}
DYLD_FALLBACK_LIBRARY_PATH=/opt/brew/lib${DYLD_FALLBACK_LIBRARY_PATH+:$DYLD_FALLBACK_LIBRARY_PATH}
C_INCLUDE_PATH=/opt/brew/include${C_INCLUDE_PATH+:$C_INCLUDE_PATH}
CPLUS_INCLUDE_PATH=/opt/brew/include${CPLUS_INCLUDE_PATH+:$CPLUS_INCLUDE_PATH}

export PATH LD_LIBRARY_PATH DYLD_FALLBACK_LIBRARY_PATH C_INCLUDE_PATH CPLUS_INCLUDE_PATH
